# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
  # gaps_in = 5
  # gaps_out = 5
    # border_size = 0

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
  #   rounding = 10
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}


animations {
    enabled = true

    # Bézier curve for a smooth "ease-out" feel
    bezier = mySmoothCurve, 0.05, 0.9, 0.1, 1.05

    # Syntax: name, enable, duration (1 = 100ms), curve, style
    
    # This is the line that controls workspace switching:
    animation = workspaces, 1, 6, mySmoothCurve, slide
}

animations {
    enabled = true
    # This bezier curve goes slightly above 1.1 to create the bounce back
    bezier = overshot, 0.05, 0.9, 0.1, 1.1

    animation = windowsIn, 1, 6, overshot, popin 70%
    animation = windowsOut, 1, 6, overshot, popin 70%
    animation = windowsMove, 1, 6, overshot, slide
}
