[colors.primary]
background = "#101315"
foreground = "#cacccc"

[colors.cursor]
text = "#101315"
cursor = "#cacccc"

[colors.vi_mode_cursor]
text = "#101315"
cursor = "#cacccc"

[colors.search.matches]
foreground = "#101315"
background = "#d9dbdc"

[colors.search.focused_match]
foreground = "#101315"
background = "#565d60"

[colors.footer_bar]
foreground = "#101315"
background = "#cacccc"

[colors.selection]
text = "#101315"
background = "#798186"

[colors.normal]
black = "#101315"
red = "#565d60"
green = "#9fa5a9"
yellow = "#d9dbdc"
blue = "#798186"
magenta = "#aeaeae"
cyan = "#707070"
white = "#cbc2be"

[colors.bright]
black = "#4b4e55"
red = "#de6145"
green = "#343d41"
yellow = "#c9c2b4"
blue = "#5d6367"
magenta = "#9a9a9a"
cyan = "#707070"
white = "#a5aeb4"
