# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#000000"

# Main text color
theme[main_fg]="#e7e9ea"

# Title color for boxes
theme[title]="#e7e9ea"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#ff8852"

# Background color of selected item in processes box
theme[selected_bg]="#626262"

# Foreground color of selected item in processes box
theme[selected_fg]="#ff8852"

# Color of inactive/disabled text
theme[inactive_fg]="#626262"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#e7e9ea"

# Background color of the percentage meters
theme[meter_bg]="#626262"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#e7e9ea"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#8a8a8a"
theme[mem_box]="#e7e9ea"
theme[net_box]="#8a8a8a"
theme[proc_box]="#ff8852"

# Box divider line and small boxes line color
theme[div_line]="#626262"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#e7e9ea"
theme[temp_mid]="#9e9e9e"
theme[temp_end]="#8a8a8a"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="#767676"
theme[cpu_mid]="#626262"
theme[cpu_end]="#8a8a8a"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="#8a8a8a"
theme[free_mid]="#626262"
theme[free_end]="#767676"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="#626262"
theme[cached_mid]="#767676"
theme[cached_end]="#8a8a8a"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#9e9e9e"
theme[available_mid]="#8a8a8a"
theme[available_end]="#8a8a8a"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#e7e9ea"
theme[used_mid]="#767676"
theme[used_end]="#626262"

# Download graph colors (Peach -> Red)
theme[download_start]="#9e9e9e"
theme[download_mid]="#8a8a8a"
theme[download_end]="#8a8a8a"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#e7e9ea"
theme[upload_mid]="#767676"
theme[upload_end]="#626262"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="#767676"
theme[process_mid]="#626262"
theme[process_end]="#8a8a8a"
