# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

$activeBorderColor = rgb(89b4fa)

general {
    col.active_border = $activeBorderColor
    gaps_in = 4
    gaps_out = 5
}

group {
    col.border_active = $activeBorderColor
}

decoration {
    rounding = 6
    rounding_power = 3
}
